In [1]:
import numpy as np
lst = [1,2,4,5]
arr = np.array(lst)
print(arr)

[1 2 4 5]


In [3]:
for i in arr:
    print(i, end = " ")

1 2 4 5 

In [9]:
arr2 = np.array(['A',12,23,34,'B'])
print(type(arr2))
for i in arr2:
    print(i, end = " ")
print(arr2.dtype)

<class 'numpy.ndarray'>
A 12 23 34 B <U11


In [20]:
lst2 = [[[1,2.5],[3,4]],[[4,5],[5,6]]]
print(lst2)
arr3 = np.array(lst2)
print(arr3.ndim)
for i in arr3:
    print(i)
print(arr3.shape)

[[[1, 2.5], [3, 4]], [[4, 5], [5, 6]]]
3
[[1.  2.5]
 [3.  4. ]]
[[4. 5.]
 [5. 6.]]
(2, 2, 2)


In [22]:
arr4 = np.zeros([3,2])
print(arr4)
arr5 = np.ones([6,4])
print(arr5)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
arr6 = np.arange(0,10,2,dtype = int)
print(arr6)

[0 2 4 6 8]


In [32]:
arr7 = np.linspace(0,20,num = 10, endpoint = True, dtype = int)
print(arr7.size)
print(arr7)

10
[ 0  2  4  6  8 11 13 15 17 20]


In [33]:
arr = np.array(lst)
print(arr)

arr2 = arr.reshape(2,2)
print(arr2)

[1 2 4 5]
[[1 2]
 [4 5]]


In [47]:
#3D list
lst3 = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,4],[3,4,6],[5,6,8]]]
for i in lst3:
    for j in i:
        for k in j:
            print(k)
        print('\n')

1
2
3


4
5
6


7
8
9


1
2
4


3
4
6


5
6
8




In [53]:
arr = np.array(lst3)
print(arr)
print('------')
arr2 = arr.reshape(-1,3,2)
print(arr2)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 4]
  [3 4 6]
  [5 6 8]]]
------
[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 1]
  [2 4]]

 [[3 4]
  [6 5]
  [6 8]]]


In [61]:
arr = np.array([1.23,34.56,42.39])
np.around(arr,2)
print([i for i in arr])
arr = np.sqrt(arr)
arr  = np.around(arr,3)
print([i for i in arr])

[1.23, 34.56, 42.39]
[1.109, 5.879, 6.511]


In [66]:
arr = np.random.rand(1,2,3)
print(arr)
val = np.sum(arr,axis = None)
print(val)

[[[0.86235945 0.66424003 0.41477947]
  [0.30002335 0.96045379 0.24220795]]]
3.444064026076634


In [72]:
nan =  np.nan
arr = np.array([nan,nan,2])
print([i for i in arr])
a1 = arr.astype(str)
print(a1)

[nan, nan, 2.0]
['nan' 'nan' '2.0']


In [76]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr1 = np.sum(arr,axis = 1)
print(arr1)
arr2 = np.sum(arr,axis = 0)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]
[12 15 18]


In [77]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.random.rand(3,3)
arr3 = np.dot(arr,arr2)
print(arr3)

[[ 1.83132828  2.19499147  3.39360235]
 [ 5.55173856  5.7547392   8.84164804]
 [ 9.27214884  9.31448694 14.28969373]]


In [85]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = arr.copy()
np.fill_diagonal(arr2,0)
print(arr2,'\n\n',arr)

[[0 2 3]
 [4 0 6]
 [7 8 0]] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [90]:
A = np.matmul(arr,arr2)
print(A)
B = np.dot(arr,arr2)
print(B)
K = np.dot(A,B)
print(A.T,'\n\n',K.T)

[[29 26 15]
 [62 56 42]
 [95 86 69]]
[[29 26 15]
 [62 56 42]
 [95 86 69]]
[[29 62 95]
 [26 56 86]
 [15 42 69]] 

 [[ 3878  9260 14642]
 [ 3500  8360 13220]
 [ 2562  6180  9798]]


In [99]:
#Accessing the array elements
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[0][1])
print(arr[1:3,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[4 5]
 [7 8]]
